const blogData = [
  {
    id: 1,
    title: 'Tầm quan trọng của xét nghiệm máu định kỳ',
    description: 'Xét nghiệm máu định kỳ giúp phát hiện sớm các vấn đề sức khỏe và theo dõi tình trạng bệnh lý hiện có.',
    imageUrl: 'https://images.unsplash.com/photo-1588776814546-b4c53b90bcbc',
    category: 'Xét nghiệm',
    readingTime: '5 phút',
    author: 'BS. Nguyễn Văn A',
    date: '15/6/2024',
  },
  // Thêm các bài viết khác...
  {
    id: 1,
    title: 'Tầm quan trọng của xét nghiệm máu định kỳ',
    description: 'Xét nghiệm máu định kỳ giúp phát hiện sớm các vấn đề sức khỏe và theo dõi tình trạng bệnh lý hiện có.',
    imageUrl: 'https://images.unsplash.com/photo-1588776814546-b4c53b90bcbc',
    category: 'Xét nghiệm',
    readingTime: '5 phút',
    author: 'BS. Nguyễn Văn A',
    date: '15/6/2024',
  },
  {
    id: 1,
    title: 'Tầm quan trọng của xét nghiệm máu định kỳ',
    description: 'Xét nghiệm máu định kỳ giúp phát hiện sớm các vấn đề sức khỏe và theo dõi tình trạng bệnh lý hiện có.',
    imageUrl: 'https://images.unsplash.com/photo-1588776814546-b4c53b90bcbc',
    category: 'Xét nghiệm',
    readingTime: '5 phút',
    author: 'BS. Nguyễn Văn A',
    date: '15/6/2024',
  },
  {
    id: 1,
    title: 'Tầm quan trọng của xét nghiệm máu định kỳ',
    description: 'Xét nghiệm máu định kỳ giúp phát hiện sớm các vấn đề sức khỏe và theo dõi tình trạng bệnh lý hiện có.',
    imageUrl: 'https://images.unsplash.com/photo-1588776814546-b4c53b90bcbc',
    category: 'Xét nghiệm',
    readingTime: '5 phút',
    author: 'BS. Nguyễn Văn A',
    date: '15/6/2024',
  },
  {
    id: 1,
    title: 'Tầm quan trọng của xét nghiệm máu định kỳ',
    description: 'Xét nghiệm máu định kỳ giúp phát hiện sớm các vấn đề sức khỏe và theo dõi tình trạng bệnh lý hiện có.',
    imageUrl: 'https://images.unsplash.com/photo-1588776814546-b4c53b90bcbc',
    category: 'Xét nghiệm',
    readingTime: '5 phút',
    author: 'BS. Nguyễn Văn A',
    date: '15/6/2024',
  },
  {
    id: 1,
    title: 'Tầm quan trọng của xét nghiệm máu định kỳ',
    description: 'Xét nghiệm máu định kỳ giúp phát hiện sớm các vấn đề sức khỏe và theo dõi tình trạng bệnh lý hiện có.',
    imageUrl: 'https://images.unsplash.com/photo-1588776814546-b4c53b90bcbc',
    category: 'Xét nghiệm',
    readingTime: '5 phút',
    author: 'BS. Nguyễn Văn A',
    date: '15/6/2024',
  },
  {
    id: 1,
    title: 'Tầm quan trọng của xét nghiệm máu định kỳ',
    description: 'Xét nghiệm máu định kỳ giúp phát hiện sớm các vấn đề sức khỏe và theo dõi tình trạng bệnh lý hiện có.',
    imageUrl: 'https://images.unsplash.com/photo-1588776814546-b4c53b90bcbc',
    category: 'Xét nghiệm',
    readingTime: '5 phút',
    author: 'BS. Nguyễn Văn A',
    date: '15/6/2024',
  },
  
];

export default blogData;
